controllers:
    resource: ../src/Controller/HomeController.php
    type: annotation

api_controllers:
    resource: ../src/Controller/ProjectController.php
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
